
version: '2'

services:

  artifactory-service:
    depends_on:
     - artifactory-mysql
    image: akhilrajmailbox/artifactory:artifactory-server
#    build:
#      context: ../dockerfiles
#      dockerfile: Dockerfile-artifactory-server
#    restart: always
    hostname: artifactory-server
    container_name: artifactory-server
    env_file: .env
    volumes:
     - $PWD/artifactory/artifactory-data:/var/opt/jfrog/artifactory:rw
    ports:
     - $PORT_NO:8081
    working_dir: /var/opt/jfrog/artifactory
    tty: true


  artifactory-mysql:
    image: mysql:5.5
#    build:
#      context: ../dockerfiles
#      dockerfile: Dockerfile-artifactory-mysql
#    restart: always
    hostname: artifactory-mysql
    container_name: artifactory-mysql
    env_file: .env
    volumes:
     - $PWD/artifactory/mysql-data:/var/lib/mysql:rw
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
    working_dir: /root
    tty: true
